Production
kensayo/micro-reddit pull request #4
Opened 2021-06-10 02:59 UTC by kensayo

2021-06-10 03:39 UTC, rindrajosia requested changes
Invalid :red_circle: 
Please use this file as linter config [.github/workflows](https://github.com/microverseinc/linters-config/blob/master/ror/.github/workflows/linters.yml)
That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

2021-06-10 17:28 UTC, taiwo2 requested changes
# STATUS: CHANGES REQUIRED ⚠️ 🚧
@kensayo Weldone for this project,Nice readme , however for this project to be approved few changes is rquired of you
Highlights:
- [x] A user can be created **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/creatingUser.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
- [x] A post can be created **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/creatingPost.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
- [ ] A comment can be created **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/creatingComment.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
- [x] kindly add `rails db:create` to your setup section in readme file
##### Post

- [x] validations are present (`body` and `title` in automated tests but can be anything else) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/postValidation.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails)).should be `text`  for your title

##### Comment

- [ ] validations are present (`body` in automated tests but can be anything else) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/commentValidation.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails)). should be `text`
kindly follow project specification.
## once specific changes made kindly request for another review

2021-06-10 23:58 UTC, mke2111 commented
## Project Under review. Please be patient. ⚪

2021-06-11 00:06 UTC, mke2111 requested changes
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**This is a great project you have going on, well-done lad and thanks for implementing the changes requested earlier on**. 

### Well-done 💯 
    1. New users and posts can be created successfully. 👍🏽 
    2. The linter checks run just fine.

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [ ] For some reason, I'm not able to create a new comment via the console. Look into this and give it a quick fix.

### OPTIONAL

- [ ] Remove all commented-out pieces of code in all your model files.

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

2021-06-11 01:41 UTC, rindrajosia requested changes
Changes Required :red_circle:
To Highlight: :angel:

- A post can be created :+1: 
- A comment can be created :100: 

To improve :factory_worker: [REQUIRED]:

- [ ] Please check the validation related to the **pwd** because I am not able to create a User even if I use the example in your readme.
![1](https://user-images.githubusercontent.com/58552748/121617564-eceaf800-ca6d-11eb-8c40-ba703742be91.gif)

Nice to have:

- [ ]  please check your readme, especially the Setup section. (check my comment below :arrow_double_down: )

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

2021-06-11 01:41 UTC, rindrajosia commented on README.md
> +- Finally go to the Ruby console with `$ rails c`
You should ask the user to use the command **rails bundle install** first then **rails db:create** after that **rails db:migrate** and finally **rails s** and/or **rails c**

2021-06-11 06:48 UTC, elisha2kyakpo1 approved these changes
# Status: Approved✔🎉💪
**Congratulations! it's time to celebrate!** I'm happy to see all the changes requested being implemented.

Cheers💪🎉

Elisha

2021-06-15 20:47 UTC, merged